//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recibos.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("recibos.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string AddReceiptButton {
            get {
                return ResourceManager.GetString("AddReceiptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturar Ubicación Actual.
        /// </summary>
        internal static string CaptureCurrentLocation {
            get {
                return ResourceManager.GetString("CaptureCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar Firma.
        /// </summary>
        internal static string ClearSignature {
            get {
                return ResourceManager.GetString("ClearSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha: {0}.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora:.
        /// </summary>
        internal static string DateTimeLabel {
            get {
                return ResourceManager.GetString("DateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar Ubicación.
        /// </summary>
        internal static string DeleteLocation {
            get {
                return ResourceManager.GetString("DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse el botón + para agregar un nuevo recibo.
        /// </summary>
        internal static string EmptyListMessage {
            get {
                return ResourceManager.GetString("EmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay recibos.
        /// </summary>
        internal static string EmptyListTitle {
            get {
                return ResourceManager.GetString("EmptyListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat: {0:F6}.
        /// </summary>
        internal static string LatitudeFormat {
            get {
                return ResourceManager.GetString("LatitudeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula: {0}.
        /// </summary>
        internal static string LicensePlateFormat {
            get {
                return ResourceManager.GetString("LicensePlateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula: .
        /// </summary>
        internal static string LicensePlateLabel {
            get {
                return ResourceManager.GetString("LicensePlateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la matrícula.
        /// </summary>
        internal static string LicensePlatePlaceholder {
            get {
                return ResourceManager.GetString("LicensePlatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga.
        /// </summary>
        internal static string LoadLabel {
            get {
                return ResourceManager.GetString("LoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación:.
        /// </summary>
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long: {0:F6}.
        /// </summary>
        internal static string LongitudeFormat {
            get {
                return ResourceManager.GetString("LongitudeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Recibo.
        /// </summary>
        internal static string NewReceiptTitle {
            get {
                return ResourceManager.GetString("NewReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin datos de ubicación.
        /// </summary>
        internal static string NoLocationData {
            get {
                return ResourceManager.GetString("NoLocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sin nota].
        /// </summary>
        internal static string NoNote {
            get {
                return ResourceManager.GetString("NoNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin fotos.
        /// </summary>
        internal static string NoPhotos {
            get {
                return ResourceManager.GetString("NoPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay fotos todavía.
        /// </summary>
        internal static string NoPhotosYet {
            get {
                return ResourceManager.GetString("NoPhotosYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin firma.
        /// </summary>
        internal static string NoSignature {
            get {
                return ResourceManager.GetString("NoSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requiere firma.
        /// </summary>
        internal static string NoSignatureRequired {
            get {
                return ResourceManager.GetString("NoSignatureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota: {0}.
        /// </summary>
        internal static string NoteFormat {
            get {
                return ResourceManager.GetString("NoteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota:.
        /// </summary>
        internal static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la nota (opcional).
        /// </summary>
        internal static string NotePlaceholder {
            get {
                return ResourceManager.GetString("NotePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sin título].
        /// </summary>
        internal static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de operación:.
        /// </summary>
        internal static string OperationTypeLabel {
            get {
                return ResourceManager.GetString("OperationTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese una nota (opcional).
        /// </summary>
        internal static string OptionalNotePlaceholder {
            get {
                return ResourceManager.GetString("OptionalNotePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el título (opcional).
        /// </summary>
        internal static string OptionalTitlePlaceholder {
            get {
                return ResourceManager.GetString("OptionalTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibos.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotografías:.
        /// </summary>
        internal static string PhotosLabel {
            get {
                return ResourceManager.GetString("PhotosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de Recibo.
        /// </summary>
        internal static string ReceiptDetailTitle {
            get {
                return ResourceManager.GetString("ReceiptDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por título o matrícula....
        /// </summary>
        internal static string SearchBarPlaceholder {
            get {
                return ResourceManager.GetString("SearchBarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma:.
        /// </summary>
        internal static string SignatureLabel {
            get {
                return ResourceManager.GetString("SignatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomar Foto.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título:.
        /// </summary>
        internal static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el título (opcional).
        /// </summary>
        internal static string TitlePlaceholder {
            get {
                return ResourceManager.GetString("TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total fotos: {0}.
        /// </summary>
        internal static string TotalPhotosFormat {
            get {
                return ResourceManager.GetString("TotalPhotosFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga.
        /// </summary>
        internal static string UnloadLabel {
            get {
                return ResourceManager.GetString("UnloadLabel", resourceCulture);
            }
        }
    }
}
